# Generated by Django 4.1 on 2022-10-23 18:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='آدرس عنوان')),
                ('description', models.TextField(max_length=2000, verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(default='image/article-image/default/article-default.jpg', upload_to='image/article-image', verbose_name='عکس')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده'), ('r', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت')),
                ('is_reported', models.BooleanField(default=False, verbose_name='گزارش شده؟')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='آدرس عنوان')),
                ('status', models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده')], default='d', max_length=1, verbose_name='وضعیت')),
                ('level', models.PositiveIntegerField(blank=True, null=True, verbose_name='سطح دسته بندی در زیرمجموعه ها')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='blog.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['parent__id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('m', 'اطلاعات علمی نادرست'), ('r', 'محتوای نامناسب و توهین آمیز'), ('o', 'موارد دیگر')], max_length=1, verbose_name='دلیل')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_checked', models.BooleanField(default=False, verbose_name='رویت شده است؟')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='مقاله مربوط')),
            ],
            options={
                'verbose_name': 'مقاله برگشت خورده',
                'verbose_name_plural': 'مقالات برگشت خورده',
            },
        ),
        migrations.CreateModel(
            name='ArticleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('m', 'اطلاعات علمی نادرست'), ('r', 'محتوای نامناسب و توهین آمیز'), ('o', 'موارد دیگر')], max_length=1, verbose_name='دلیل')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_checked', models.BooleanField(default=False, verbose_name='بررسی شده است؟')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleReport', to='blog.article', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'مقاله گزارش داده شده',
                'verbose_name_plural': 'مقالات گزارش داده شده',
            },
        ),
    ]
